-- =====================================================================
-- MERCADO — SEED v1 (dados reais, Out/2026). RODAR DEPOIS do mercado_ddl_v1.sql.
-- Decisões travadas: (A) VIRAR TUDO para 2026/27 como corrente — elencos avançam p/
--   season=2026 E is_current passa p/ 26/27 (o resto é passado, acessível por seletor);
--   multas do banco são descartadas e resemeadas desta extração.
-- Joins por start_year (seasons.label '26/27' != contract '2026-27').
-- =====================================================================

BEGIN;

-- -------- (A) Avançar elencos 2025 -> 2026 --------
-- PRECHECK (deve retornar 0): select count(*) from roster_entries where season=2026;
update roster_entries set season = 2026, updated_at = now() where season = 2025;

-- is_current -> 26/27 (virar tudo para a temporada atual).
-- COORDENAR com o repoint do frontend (ver .md): rodar JUNTO do deploy que aponta
-- as telas p/ 26/27, senão /times, /elencos e as páginas de stats quebram no intervalo
-- (26/27 ainda não tem jogos).
update seasons set is_current = false where is_current = true;
update seasons set is_current = true  where start_year = 2026;

-- -------- Multas: limpar e resemear (49 linhas limpas da planilha) --------
delete from team_penalties;
insert into team_penalties (team_id, season_id, amount, source)
select t.id, s.id, v.amount, 'manual'
from (values
  ($$Floripa Waves$$, 2026, 1100000),
  ($$Cambuquira Pure Water$$, 2026, 1800000),
  ($$Cambuquira Pure Water$$, 2027, 2550000),
  ($$Pará Papão$$, 2026, 350000),
  ($$Pará Papão$$, 2027, 250000),
  ($$Pará Papão$$, 2028, 250000),
  ($$Goiânia Old Devils$$, 2026, 550000),
  ($$Goiânia Old Devils$$, 2027, 250000),
  ($$Goiânia Old Devils$$, 2028, 250000),
  ($$Goiânia Old Devils$$, 2029, 250000),
  ($$Tijuca Rocks$$, 2026, 3550000),
  ($$SP Horse Ride$$, 2027, 550000),
  ($$SP Horse Ride$$, 2028, 1500000),
  ($$SP Horse Ride$$, 2029, 1500000),
  ($$Brasilia Carcarás$$, 2027, 1500000),
  ($$JPA KissFlowers$$, 2026, 1950000),
  ($$JPA KissFlowers$$, 2027, 250000),
  ($$João Pessoa Fats$$, 2026, 4550000),
  ($$João Pessoa Fats$$, 2027, 4300000),
  ($$João Pessoa Fats$$, 2028, 1300000),
  ($$João Pessoa Fats$$, 2029, 250000),
  ($$Prudente Bengals$$, 2026, 3900000),
  ($$Prudente Bengals$$, 2027, 250000),
  ($$Recife Gold Lions$$, 2026, 4700000),
  ($$Recife Gold Lions$$, 2027, 1400000),
  ($$Recife Gold Lions$$, 2028, 1400000),
  ($$Recife Gold Lions$$, 2029, 1400000),
  ($$Campos Oilers$$, 2027, 1000000),
  ($$Rio Preto Capivaras$$, 2026, 700000),
  ($$Rio Preto Capivaras$$, 2027, 20000),
  ($$Rio Preto Capivaras$$, 2028, 200000),
  ($$RJ Drugdealers$$, 2026, 3650000),
  ($$RJ Drugdealers$$, 2027, 2550000),
  ($$RJ Drugdealers$$, 2028, 200000),
  ($$RJ Drugdealers$$, 2029, 200000),
  ($$Porto Alegre Ornitorrincos$$, 2026, 1950000),
  ($$Dengue State Outlawz$$, 2026, 500000),
  ($$Dengue State Outlawz$$, 2027, 750000),
  ($$Dengue State Outlawz$$, 2028, 450000),
  ($$Dengue State Outlawz$$, 2029, 100000),
  ($$Pinheiros Racecars$$, 2026, 2100000),
  ($$Lavras Big Balls$$, 2026, 4250000),
  ($$Santo André Balboas$$, 2026, 1350000),
  ($$Campinas Color Blinds$$, 2026, 600000),
  ($$Campos Lighthalzen$$, 2026, 250000),
  ($$Campos Lighthalzen$$, 2027, 2050000),
  ($$Campos Lighthalzen$$, 2028, 1300000),
  ($$Campos Lighthalzen$$, 2029, 200000),
  ($$Campos Lighthalzen$$, 2030, 200000)
) as v(team_name, start_year, amount)
join teams t on t.name = v.team_name and t.is_active
join seasons s on s.start_year = v.start_year;

delete from draft_picks;
-- -------- Picks (191); os 2 conflitos entram com disputed=true --------
insert into draft_picks (draft_season_id, round, original_team_id, current_team_id, disputed)
select s.id, v.round, ot.id, ct.id, v.disputed
from (values
  (2027, 1, $$Floripa Waves$$, $$Floripa Waves$$, false),
  (2028, 2, $$Porto Alegre Ornitorrincos$$, $$Floripa Waves$$, false),
  (2030, 1, $$Floripa Waves$$, $$Floripa Waves$$, false),
  (2028, 2, $$Campos Lighthalzen$$, $$Floripa Waves$$, false),
  (2030, 2, $$Floripa Waves$$, $$Floripa Waves$$, false),
  (2027, 1, $$Cambuquira Pure Water$$, $$Cambuquira Pure Water$$, false),
  (2028, 1, $$Cambuquira Pure Water$$, $$Cambuquira Pure Water$$, false),
  (2029, 1, $$Cambuquira Pure Water$$, $$Cambuquira Pure Water$$, false),
  (2030, 1, $$Cambuquira Pure Water$$, $$Cambuquira Pure Water$$, false),
  (2027, 2, $$Cambuquira Pure Water$$, $$Cambuquira Pure Water$$, false),
  (2028, 2, $$Cambuquira Pure Water$$, $$Cambuquira Pure Water$$, false),
  (2029, 2, $$Cambuquira Pure Water$$, $$Cambuquira Pure Water$$, false),
  (2030, 2, $$Cambuquira Pure Water$$, $$Cambuquira Pure Water$$, false),
  (2027, 1, $$Pará Papão$$, $$Pará Papão$$, false),
  (2028, 1, $$Pará Papão$$, $$Pará Papão$$, false),
  (2029, 1, $$Pará Papão$$, $$Pará Papão$$, false),
  (2030, 1, $$Pará Papão$$, $$Pará Papão$$, false),
  (2027, 1, $$João Pessoa Fats$$, $$Pará Papão$$, false),
  (2028, 2, $$Pará Papão$$, $$Pará Papão$$, false),
  (2029, 2, $$Pará Papão$$, $$Pará Papão$$, false),
  (2030, 2, $$Pará Papão$$, $$Pará Papão$$, false),
  (2027, 2, $$Pará Papão$$, $$Pará Papão$$, false),
  (2027, 1, $$Goiânia Old Devils$$, $$Goiânia Old Devils$$, false),
  (2028, 1, $$Goiânia Old Devils$$, $$Goiânia Old Devils$$, false),
  (2029, 1, $$Goiânia Old Devils$$, $$Goiânia Old Devils$$, false),
  (2030, 1, $$Goiânia Old Devils$$, $$Goiânia Old Devils$$, false),
  (2027, 2, $$Goiânia Old Devils$$, $$Goiânia Old Devils$$, false),
  (2028, 2, $$Goiânia Old Devils$$, $$Goiânia Old Devils$$, false),
  (2029, 2, $$Goiânia Old Devils$$, $$Goiânia Old Devils$$, false),
  (2030, 2, $$Goiânia Old Devils$$, $$Goiânia Old Devils$$, false),
  (2027, 1, $$Tijuca Rocks$$, $$Tijuca Rocks$$, false),
  (2028, 1, $$Tijuca Rocks$$, $$Tijuca Rocks$$, false),
  (2029, 1, $$Tijuca Rocks$$, $$Tijuca Rocks$$, false),
  (2030, 1, $$Tijuca Rocks$$, $$Tijuca Rocks$$, false),
  (2027, 2, $$Tijuca Rocks$$, $$Tijuca Rocks$$, false),
  (2028, 2, $$Tijuca Rocks$$, $$Tijuca Rocks$$, false),
  (2029, 2, $$Tijuca Rocks$$, $$Tijuca Rocks$$, false),
  (2030, 2, $$Tijuca Rocks$$, $$Tijuca Rocks$$, false),
  (2027, 2, $$Campinas Color Blinds$$, $$Tijuca Rocks$$, false),
  (2029, 2, $$Floripa Waves$$, $$Tijuca Rocks$$, false),
  (2027, 2, $$Brasilia Carcarás$$, $$Tijuca Rocks$$, false),
  (2028, 2, $$Brasilia Carcarás$$, $$Tijuca Rocks$$, false),
  (2027, 2, $$Dengue State Outlawz$$, $$SP Horse Ride$$, false),
  (2028, 1, $$SP Horse Ride$$, $$SP Horse Ride$$, false),
  (2029, 1, $$Floripa Waves$$, $$SP Horse Ride$$, false),
  (2030, 1, $$SP Horse Ride$$, $$SP Horse Ride$$, false),
  (2027, 2, $$Rio Preto Capivaras$$, $$SP Horse Ride$$, false),
  (2029, 2, $$SP Horse Ride$$, $$SP Horse Ride$$, false),
  (2030, 2, $$SP Horse Ride$$, $$SP Horse Ride$$, false),
  (2027, 2, $$Campos Lighthalzen$$, $$SP Horse Ride$$, false),
  (2028, 1, $$Brasilia Carcarás$$, $$Brasilia Carcarás$$, false),
  (2029, 1, $$Brasilia Carcarás$$, $$Brasilia Carcarás$$, false),
  (2030, 1, $$Brasilia Carcarás$$, $$Brasilia Carcarás$$, false),
  (2027, 1, $$JPA KissFlowers$$, $$JPA KissFlowers$$, false),
  (2028, 1, $$JPA KissFlowers$$, $$JPA KissFlowers$$, false),
  (2029, 1, $$JPA KissFlowers$$, $$JPA KissFlowers$$, false),
  (2030, 1, $$JPA KissFlowers$$, $$JPA KissFlowers$$, false),
  (2027, 2, $$JPA KissFlowers$$, $$JPA KissFlowers$$, false),
  (2028, 2, $$JPA KissFlowers$$, $$JPA KissFlowers$$, false),
  (2029, 2, $$JPA KissFlowers$$, $$JPA KissFlowers$$, false),
  (2030, 2, $$JPA KissFlowers$$, $$JPA KissFlowers$$, false),
  (2027, 2, $$João Pessoa Fats$$, $$JPA KissFlowers$$, false),
  (2027, 2, $$Lavras Big Balls$$, $$João Pessoa Fats$$, false),
  (2028, 1, $$João Pessoa Fats$$, $$João Pessoa Fats$$, false),
  (2029, 1, $$João Pessoa Fats$$, $$João Pessoa Fats$$, false),
  (2030, 1, $$João Pessoa Fats$$, $$João Pessoa Fats$$, false),
  (2028, 2, $$João Pessoa Fats$$, $$João Pessoa Fats$$, false),
  (2029, 2, $$João Pessoa Fats$$, $$João Pessoa Fats$$, false),
  (2030, 2, $$João Pessoa Fats$$, $$João Pessoa Fats$$, false),
  (2027, 1, $$Prudente Bengals$$, $$Prudente Bengals$$, false),
  (2028, 1, $$Prudente Bengals$$, $$Prudente Bengals$$, false),
  (2029, 1, $$Prudente Bengals$$, $$Prudente Bengals$$, false),
  (2030, 1, $$Prudente Bengals$$, $$Prudente Bengals$$, false),
  (2027, 2, $$Prudente Bengals$$, $$Prudente Bengals$$, false),
  (2028, 2, $$Prudente Bengals$$, $$Prudente Bengals$$, false),
  (2029, 2, $$Prudente Bengals$$, $$Prudente Bengals$$, false),
  (2030, 2, $$Prudente Bengals$$, $$Prudente Bengals$$, false),
  (2027, 1, $$Palmas Mamiferos$$, $$Palmas Mamiferos$$, false),
  (2028, 1, $$Palmas Mamiferos$$, $$Palmas Mamiferos$$, false),
  (2029, 1, $$Palmas Mamiferos$$, $$Palmas Mamiferos$$, false),
  (2030, 1, $$Palmas Mamiferos$$, $$Palmas Mamiferos$$, false),
  (2027, 2, $$Palmas Mamiferos$$, $$Palmas Mamiferos$$, false),
  (2028, 2, $$Palmas Mamiferos$$, $$Palmas Mamiferos$$, false),
  (2029, 2, $$Palmas Mamiferos$$, $$Palmas Mamiferos$$, false),
  (2030, 2, $$Palmas Mamiferos$$, $$Palmas Mamiferos$$, false),
  (2027, 1, $$Recife Gold Lions$$, $$Recife Gold Lions$$, false),
  (2028, 1, $$Recife Gold Lions$$, $$Recife Gold Lions$$, false),
  (2029, 1, $$Recife Gold Lions$$, $$Recife Gold Lions$$, false),
  (2030, 1, $$Recife Gold Lions$$, $$Recife Gold Lions$$, false),
  (2027, 1, $$SP Horse Ride$$, $$Recife Gold Lions$$, false),
  (2028, 2, $$Recife Gold Lions$$, $$Recife Gold Lions$$, false),
  (2029, 2, $$Recife Gold Lions$$, $$Recife Gold Lions$$, false),
  (2030, 2, $$Recife Gold Lions$$, $$Recife Gold Lions$$, false),
  (2027, 2, $$SP Horse Ride$$, $$Recife Gold Lions$$, false),
  (2028, 1, $$Campos Lighthalzen$$, $$Recife Gold Lions$$, true),
  (2028, 1, $$Campos Oilers$$, $$Campos Oilers$$, false),
  (2029, 1, $$Campos Oilers$$, $$Campos Oilers$$, false),
  (2030, 1, $$Campos Oilers$$, $$Campos Oilers$$, false),
  (2029, 2, $$Campos Oilers$$, $$Campos Oilers$$, false),
  (2030, 2, $$Campos Oilers$$, $$Campos Oilers$$, false),
  (2027, 1, $$Blumenau Assassins$$, $$Blumenau Assassins$$, false),
  (2028, 1, $$Blumenau Assassins$$, $$Blumenau Assassins$$, false),
  (2029, 1, $$Blumenau Assassins$$, $$Blumenau Assassins$$, false),
  (2030, 1, $$Blumenau Assassins$$, $$Blumenau Assassins$$, false),
  (2027, 2, $$Blumenau Assassins$$, $$Blumenau Assassins$$, false),
  (2028, 2, $$Blumenau Assassins$$, $$Blumenau Assassins$$, false),
  (2029, 2, $$Blumenau Assassins$$, $$Blumenau Assassins$$, false),
  (2030, 2, $$Blumenau Assassins$$, $$Blumenau Assassins$$, false),
  (2028, 1, $$Rio Preto Capivaras$$, $$Rio Preto Capivaras$$, false),
  (2029, 1, $$Rio Preto Capivaras$$, $$Rio Preto Capivaras$$, false),
  (2030, 1, $$Rio Preto Capivaras$$, $$Rio Preto Capivaras$$, false),
  (2028, 2, $$Rio Preto Capivaras$$, $$Rio Preto Capivaras$$, false),
  (2029, 1, $$SP Horse Ride$$, $$Rio Preto Capivaras$$, false),
  (2030, 2, $$Rio Preto Capivaras$$, $$Rio Preto Capivaras$$, false),
  (2028, 1, $$RJ Drugdealers$$, $$RJ Drugdealers$$, false),
  (2029, 1, $$RJ Drugdealers$$, $$RJ Drugdealers$$, false),
  (2030, 1, $$RJ Drugdealers$$, $$RJ Drugdealers$$, false),
  (2027, 2, $$RJ Drugdealers$$, $$RJ Drugdealers$$, false),
  (2028, 2, $$RJ Drugdealers$$, $$RJ Drugdealers$$, false),
  (2029, 2, $$RJ Drugdealers$$, $$RJ Drugdealers$$, false),
  (2030, 2, $$RJ Drugdealers$$, $$RJ Drugdealers$$, false),
  (2029, 2, $$Dengue State Outlawz$$, $$RJ Drugdealers$$, false),
  (2027, 1, $$Porto Alegre Ornitorrincos$$, $$Porto Alegre Ornitorrincos$$, false),
  (2028, 1, $$Porto Alegre Ornitorrincos$$, $$Porto Alegre Ornitorrincos$$, false),
  (2029, 1, $$Porto Alegre Ornitorrincos$$, $$Porto Alegre Ornitorrincos$$, false),
  (2030, 1, $$Porto Alegre Ornitorrincos$$, $$Porto Alegre Ornitorrincos$$, false),
  (2027, 1, $$Campos Oilers$$, $$Porto Alegre Ornitorrincos$$, false),
  (2028, 2, $$Floripa Waves$$, $$Porto Alegre Ornitorrincos$$, true),
  (2029, 2, $$Porto Alegre Ornitorrincos$$, $$Porto Alegre Ornitorrincos$$, false),
  (2030, 2, $$Porto Alegre Ornitorrincos$$, $$Porto Alegre Ornitorrincos$$, false),
  (2027, 2, $$Porto Alegre Ornitorrincos$$, $$Porto Alegre Ornitorrincos$$, false),
  (2028, 2, $$Campos Oilers$$, $$Porto Alegre Ornitorrincos$$, false),
  (2030, 2, $$Brasilia Carcarás$$, $$Porto Alegre Ornitorrincos$$, false),
  (2027, 1, $$Brasilia Carcarás$$, $$Dengue State Outlawz$$, false),
  (2028, 1, $$Dengue State Outlawz$$, $$Dengue State Outlawz$$, false),
  (2029, 1, $$Dengue State Outlawz$$, $$Dengue State Outlawz$$, false),
  (2030, 1, $$Dengue State Outlawz$$, $$Dengue State Outlawz$$, false),
  (2027, 2, $$Recife Gold Lions$$, $$Dengue State Outlawz$$, false),
  (2028, 2, $$Dengue State Outlawz$$, $$Dengue State Outlawz$$, false),
  (2030, 2, $$Dengue State Outlawz$$, $$Dengue State Outlawz$$, false),
  (2027, 1, $$Pinheiros Racecars$$, $$Pinheiros Racecars$$, false),
  (2028, 1, $$Pinheiros Racecars$$, $$Pinheiros Racecars$$, false),
  (2029, 1, $$Pinheiros Racecars$$, $$Pinheiros Racecars$$, false),
  (2030, 1, $$Pinheiros Racecars$$, $$Pinheiros Racecars$$, false),
  (2027, 2, $$Pinheiros Racecars$$, $$Pinheiros Racecars$$, false),
  (2028, 2, $$Pinheiros Racecars$$, $$Pinheiros Racecars$$, false),
  (2029, 2, $$Pinheiros Racecars$$, $$Pinheiros Racecars$$, false),
  (2030, 2, $$Pinheiros Racecars$$, $$Pinheiros Racecars$$, false),
  (2027, 1, $$Lavras Big Balls$$, $$Lavras Big Balls$$, false),
  (2028, 1, $$Lavras Big Balls$$, $$Lavras Big Balls$$, false),
  (2029, 1, $$Lavras Big Balls$$, $$Lavras Big Balls$$, false),
  (2030, 1, $$Lavras Big Balls$$, $$Lavras Big Balls$$, false),
  (2027, 1, $$Dengue State Outlawz$$, $$Lavras Big Balls$$, false),
  (2028, 1, $$Floripa Waves$$, $$Lavras Big Balls$$, false),
  (2029, 2, $$Lavras Big Balls$$, $$Lavras Big Balls$$, false),
  (2030, 2, $$Lavras Big Balls$$, $$Lavras Big Balls$$, false),
  (2027, 2, $$Floripa Waves$$, $$Lavras Big Balls$$, false),
  (2028, 2, $$Lavras Big Balls$$, $$Lavras Big Balls$$, false),
  (2029, 2, $$Brasilia Carcarás$$, $$Lavras Big Balls$$, false),
  (2028, 2, $$Floripa Waves$$, $$Lavras Big Balls$$, true),
  (2027, 1, $$Santo André Balboas$$, $$Santo André Balboas$$, false),
  (2028, 1, $$Santo André Balboas$$, $$Santo André Balboas$$, false),
  (2029, 1, $$Santo André Balboas$$, $$Santo André Balboas$$, false),
  (2030, 1, $$Santo André Balboas$$, $$Santo André Balboas$$, false),
  (2027, 1, $$Rio Preto Capivaras$$, $$Santo André Balboas$$, false),
  (2028, 2, $$Santo André Balboas$$, $$Santo André Balboas$$, false),
  (2029, 2, $$Santo André Balboas$$, $$Santo André Balboas$$, false),
  (2030, 2, $$Santo André Balboas$$, $$Santo André Balboas$$, false),
  (2027, 1, $$RJ Drugdealers$$, $$Santo André Balboas$$, false),
  (2028, 1, $$Campos Lighthalzen$$, $$Santo André Balboas$$, true),
  (2027, 2, $$Santo André Balboas$$, $$Santo André Balboas$$, false),
  (2027, 1, $$São Paulo TrafficJam$$, $$São Paulo TrafficJam$$, false),
  (2028, 1, $$São Paulo TrafficJam$$, $$São Paulo TrafficJam$$, false),
  (2029, 1, $$São Paulo TrafficJam$$, $$São Paulo TrafficJam$$, false),
  (2030, 1, $$São Paulo TrafficJam$$, $$São Paulo TrafficJam$$, false),
  (2028, 2, $$São Paulo TrafficJam$$, $$São Paulo TrafficJam$$, false),
  (2029, 2, $$São Paulo TrafficJam$$, $$São Paulo TrafficJam$$, false),
  (2030, 2, $$São Paulo TrafficJam$$, $$São Paulo TrafficJam$$, false),
  (2027, 1, $$Campinas Color Blinds$$, $$Campinas Color Blinds$$, false),
  (2028, 1, $$Campinas Color Blinds$$, $$Campinas Color Blinds$$, false),
  (2029, 1, $$Campinas Color Blinds$$, $$Campinas Color Blinds$$, false),
  (2030, 1, $$Campinas Color Blinds$$, $$Campinas Color Blinds$$, false),
  (2028, 2, $$Campinas Color Blinds$$, $$Campinas Color Blinds$$, false),
  (2029, 2, $$Campinas Color Blinds$$, $$Campinas Color Blinds$$, false),
  (2030, 2, $$Campinas Color Blinds$$, $$Campinas Color Blinds$$, false),
  (2027, 2, $$São Paulo TrafficJam$$, $$Campos Lighthalzen$$, false),
  (2029, 1, $$Campos Lighthalzen$$, $$Campos Lighthalzen$$, false),
  (2030, 1, $$Campos Lighthalzen$$, $$Campos Lighthalzen$$, false),
  (2028, 2, $$SP Horse Ride$$, $$Campos Lighthalzen$$, false),
  (2029, 2, $$Campos Lighthalzen$$, $$Campos Lighthalzen$$, false),
  (2030, 2, $$Campos Lighthalzen$$, $$Campos Lighthalzen$$, false)
) as v(start_year, round, orig_name, curr_name, disputed)
join seasons s on s.start_year = v.start_year
join teams ot on ot.name = v.orig_name and ot.is_active
join teams ct on ct.name = v.curr_name and ct.is_active;

COMMIT;

-- Conferência pós-seed (rode DEPOIS do COMMIT):
-- select count(*) from draft_picks;                      -- esperado 191
-- select count(*) from draft_picks where disputed;       -- esperado 4 (2 picks x2 donos)
-- select count(*) from team_penalties;                   -- esperado 49
