/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegrasRouteImport } from './routes/regras'
import { Route as RecordesRouteImport } from './routes/recordes'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MediasRouteImport } from './routes/medias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GmsRouteImport } from './routes/gms'
import { Route as FreeAgentsRouteImport } from './routes/free-agents'
import { Route as EscalarRouteImport } from './routes/escalar'
import { Route as EscalacoesRouteImport } from './routes/escalacoes'
import { Route as ElencosRouteImport } from './routes/elencos'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesSlugRouteImport } from './routes/times_.$slug'
import { Route as AdminFecharSemanaRouteImport } from './routes/admin.fechar-semana'
import { Route as AdminConsolidarLockRouteImport } from './routes/admin.consolidar-lock'

const RegrasRoute = RegrasRouteImport.update({
  id: '/regras',
  path: '/regras',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordesRoute = RecordesRouteImport.update({
  id: '/recordes',
  path: '/recordes',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MediasRoute = MediasRouteImport.update({
  id: '/medias',
  path: '/medias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GmsRoute = GmsRouteImport.update({
  id: '/gms',
  path: '/gms',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAgentsRoute = FreeAgentsRouteImport.update({
  id: '/free-agents',
  path: '/free-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalarRoute = EscalarRouteImport.update({
  id: '/escalar',
  path: '/escalar',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalacoesRoute = EscalacoesRouteImport.update({
  id: '/escalacoes',
  path: '/escalacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ElencosRoute = ElencosRouteImport.update({
  id: '/elencos',
  path: '/elencos',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesSlugRoute = TimesSlugRouteImport.update({
  id: '/times_/$slug',
  path: '/times/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFecharSemanaRoute = AdminFecharSemanaRouteImport.update({
  id: '/admin/fechar-semana',
  path: '/admin/fechar-semana',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsolidarLockRoute = AdminConsolidarLockRouteImport.update({
  id: '/admin/consolidar-lock',
  path: '/admin/consolidar-lock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/draft': typeof DraftRoute
  '/elencos': typeof ElencosRoute
  '/escalacoes': typeof EscalacoesRoute
  '/escalar': typeof EscalarRoute
  '/free-agents': typeof FreeAgentsRoute
  '/gms': typeof GmsRoute
  '/login': typeof LoginRoute
  '/medias': typeof MediasRoute
  '/noticias': typeof NoticiasRoute
  '/recordes': typeof RecordesRoute
  '/regras': typeof RegrasRoute
  '/admin/consolidar-lock': typeof AdminConsolidarLockRoute
  '/admin/fechar-semana': typeof AdminFecharSemanaRoute
  '/times/$slug': typeof TimesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/draft': typeof DraftRoute
  '/elencos': typeof ElencosRoute
  '/escalacoes': typeof EscalacoesRoute
  '/escalar': typeof EscalarRoute
  '/free-agents': typeof FreeAgentsRoute
  '/gms': typeof GmsRoute
  '/login': typeof LoginRoute
  '/medias': typeof MediasRoute
  '/noticias': typeof NoticiasRoute
  '/recordes': typeof RecordesRoute
  '/regras': typeof RegrasRoute
  '/admin/consolidar-lock': typeof AdminConsolidarLockRoute
  '/admin/fechar-semana': typeof AdminFecharSemanaRoute
  '/times/$slug': typeof TimesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/classificacao': typeof ClassificacaoRoute
  '/draft': typeof DraftRoute
  '/elencos': typeof ElencosRoute
  '/escalacoes': typeof EscalacoesRoute
  '/escalar': typeof EscalarRoute
  '/free-agents': typeof FreeAgentsRoute
  '/gms': typeof GmsRoute
  '/login': typeof LoginRoute
  '/medias': typeof MediasRoute
  '/noticias': typeof NoticiasRoute
  '/recordes': typeof RecordesRoute
  '/regras': typeof RegrasRoute
  '/admin/consolidar-lock': typeof AdminConsolidarLockRoute
  '/admin/fechar-semana': typeof AdminFecharSemanaRoute
  '/times_/$slug': typeof TimesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/classificacao'
    | '/draft'
    | '/elencos'
    | '/escalacoes'
    | '/escalar'
    | '/free-agents'
    | '/gms'
    | '/login'
    | '/medias'
    | '/noticias'
    | '/recordes'
    | '/regras'
    | '/admin/consolidar-lock'
    | '/admin/fechar-semana'
    | '/times/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/classificacao'
    | '/draft'
    | '/elencos'
    | '/escalacoes'
    | '/escalar'
    | '/free-agents'
    | '/gms'
    | '/login'
    | '/medias'
    | '/noticias'
    | '/recordes'
    | '/regras'
    | '/admin/consolidar-lock'
    | '/admin/fechar-semana'
    | '/times/$slug'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/classificacao'
    | '/draft'
    | '/elencos'
    | '/escalacoes'
    | '/escalar'
    | '/free-agents'
    | '/gms'
    | '/login'
    | '/medias'
    | '/noticias'
    | '/recordes'
    | '/regras'
    | '/admin/consolidar-lock'
    | '/admin/fechar-semana'
    | '/times_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  DraftRoute: typeof DraftRoute
  ElencosRoute: typeof ElencosRoute
  EscalacoesRoute: typeof EscalacoesRoute
  EscalarRoute: typeof EscalarRoute
  FreeAgentsRoute: typeof FreeAgentsRoute
  GmsRoute: typeof GmsRoute
  LoginRoute: typeof LoginRoute
  MediasRoute: typeof MediasRoute
  NoticiasRoute: typeof NoticiasRoute
  RecordesRoute: typeof RecordesRoute
  RegrasRoute: typeof RegrasRoute
  AdminConsolidarLockRoute: typeof AdminConsolidarLockRoute
  AdminFecharSemanaRoute: typeof AdminFecharSemanaRoute
  TimesSlugRoute: typeof TimesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regras': {
      id: '/regras'
      path: '/regras'
      fullPath: '/regras'
      preLoaderRoute: typeof RegrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordes': {
      id: '/recordes'
      path: '/recordes'
      fullPath: '/recordes'
      preLoaderRoute: typeof RecordesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medias': {
      id: '/medias'
      path: '/medias'
      fullPath: '/medias'
      preLoaderRoute: typeof MediasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gms': {
      id: '/gms'
      path: '/gms'
      fullPath: '/gms'
      preLoaderRoute: typeof GmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-agents': {
      id: '/free-agents'
      path: '/free-agents'
      fullPath: '/free-agents'
      preLoaderRoute: typeof FreeAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalar': {
      id: '/escalar'
      path: '/escalar'
      fullPath: '/escalar'
      preLoaderRoute: typeof EscalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalacoes': {
      id: '/escalacoes'
      path: '/escalacoes'
      fullPath: '/escalacoes'
      preLoaderRoute: typeof EscalacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elencos': {
      id: '/elencos'
      path: '/elencos'
      fullPath: '/elencos'
      preLoaderRoute: typeof ElencosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times_/$slug': {
      id: '/times_/$slug'
      path: '/times/$slug'
      fullPath: '/times/$slug'
      preLoaderRoute: typeof TimesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fechar-semana': {
      id: '/admin/fechar-semana'
      path: '/admin/fechar-semana'
      fullPath: '/admin/fechar-semana'
      preLoaderRoute: typeof AdminFecharSemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/consolidar-lock': {
      id: '/admin/consolidar-lock'
      path: '/admin/consolidar-lock'
      fullPath: '/admin/consolidar-lock'
      preLoaderRoute: typeof AdminConsolidarLockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  DraftRoute: DraftRoute,
  ElencosRoute: ElencosRoute,
  EscalacoesRoute: EscalacoesRoute,
  EscalarRoute: EscalarRoute,
  FreeAgentsRoute: FreeAgentsRoute,
  GmsRoute: GmsRoute,
  LoginRoute: LoginRoute,
  MediasRoute: MediasRoute,
  NoticiasRoute: NoticiasRoute,
  RecordesRoute: RecordesRoute,
  RegrasRoute: RegrasRoute,
  AdminConsolidarLockRoute: AdminConsolidarLockRoute,
  AdminFecharSemanaRoute: AdminFecharSemanaRoute,
  TimesSlugRoute: TimesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
